### ISSUE TITLE
Ran last chunk of radiant-mlhub-api-know-how.ipynb but get error 403: Forbidden

### ISSUE THREAD

**Issue by billeerds** [radiantearth/mlhub-tutorials#15]
I am going through the how to jupyter notebook. I created a general secret in AWS and try to run the last chunk of code. I have removed my access key and secret key. However, I get an error 403: forbidden error when trying to access the sentinel image data. Can radiantearth only access these images?

`import boto3
AWS_ACCESS_KEY_ID = ''
AWS_SECRET_KEY = ''

def download_s3_file(url, access_key, secret_key):
    parsed_url = urlparse(url)
    
    bucket = parsed_url.hostname.split('.')[0]
    path = parsed_url.path[1:]
    filename = path.split('/')[-1]
    
    s3 = boto3.client(
        's3',
        aws_access_key_id=AWS_ACCESS_KEY_ID,
        aws_secret_access_key=AWS_SECRET_KEY
    )
    
    s3.download_file(bucket, path, filename, ExtraArgs={'RequestPayer': 'requester'})
    print(f'Downloaded s3://{bucket}/{path}')`

Error below:
`---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
<ipython-input-12-6f7fcd054d56> in <module>()
      1 true_color_asset_url = get_download_url(selected_item, '2019_07_31_tci', headers)
----> 2 download_s3_file(true_color_asset_url, AWS_ACCESS_KEY_ID, AWS_SECRET_KEY)

<ipython-input-11-535ffbea490b> in download_s3_file(url, access_key, secret_key)
     16     )
     17 
---> 18     s3.download_file(bucket, path, filename, ExtraArgs={'RequestPayer': 'requester'})
     19     print(f'Downloaded s3://{bucket}/{path}')

~\Anaconda2\envs\py36\lib\site-packages\boto3\s3\inject.py in download_file(self, Bucket, Key, Filename, ExtraArgs, Callback, Config)
    170         return transfer.download_file(
    171             bucket=Bucket, key=Key, filename=Filename,
--> 172             extra_args=ExtraArgs, callback=Callback)
    173 
    174 

~\Anaconda2\envs\py36\lib\site-packages\boto3\s3\transfer.py in download_file(self, bucket, key, filename, extra_args, callback)
    305             bucket, key, filename, extra_args, subscribers)
    306         try:
--> 307             future.result()
    308         # This is for backwards compatibility where when retries are
    309         # exceeded we need to throw the same error from boto3 instead of

~\Anaconda2\envs\py36\lib\site-packages\s3transfer\futures.py in result(self)
    104             # however if a KeyboardInterrupt is raised we want want to exit
    105             # out of this and propogate the exception.
--> 106             return self._coordinator.result()
    107         except KeyboardInterrupt as e:
    108             self.cancel()

~\Anaconda2\envs\py36\lib\site-packages\s3transfer\futures.py in result(self)
    263         # final result.
    264         if self._exception:
--> 265             raise self._exception
    266         return self._result
    267 

~\Anaconda2\envs\py36\lib\site-packages\s3transfer\tasks.py in _main(self, transfer_future, **kwargs)
    253             # Call the submit method to start submitting tasks to execute the
    254             # transfer.
--> 255             self._submit(transfer_future=transfer_future, **kwargs)
    256         except BaseException as e:
    257             # If there was an exception raised during the submission of task

~\Anaconda2\envs\py36\lib\site-packages\s3transfer\download.py in _submit(self, client, config, osutil, request_executor, io_executor, transfer_future, bandwidth_limiter)
    341                 Bucket=transfer_future.meta.call_args.bucket,
    342                 Key=transfer_future.meta.call_args.key,
--> 343                 **transfer_future.meta.call_args.extra_args
    344             )
    345             transfer_future.meta.provide_transfer_size(

~\Anaconda2\envs\py36\lib\site-packages\botocore\client.py in _api_call(self, *args, **kwargs)
    274                     "%s() only accepts keyword arguments." % py_operation_name)
    275             # The "self" in this scope is referring to the BaseClient.
--> 276             return self._make_api_call(operation_name, kwargs)
    277 
    278         _api_call.__name__ = str(py_operation_name)

~\Anaconda2\envs\py36\lib\site-packages\botocore\client.py in _make_api_call(self, operation_name, api_params)
    584             error_code = parsed_response.get("Error", {}).get("Code")
    585             error_class = self.exceptions.from_code(error_code)
--> 586             raise error_class(parsed_response, operation_name)
    587         else:
    588             return parsed_response

ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden`

**Comment by kbgg** [comment]
Hi Bill,

The [bucket that the Sentinel-2 imagery is hosted on](https://registry.opendata.aws/sentinel-2/) is managed by Sinergise, not Radiant Earth. Since the bucket is in Requester Pays mode, the user downloading the imagery will be billed for the data transfer costs. Make sure the AWS account you are downloading with has a valid credit card attached and the user for your access key has permissions to download objects from a bucket.

Let me know if this resolves your issue!

Best,
Kevin

**Comment by billeerds** [comment]
Hey Kevin!

I am a novice. Thanks for the help! Had to create an IAM first and then set the bucket as seen below:

s3 = boto3.client(
        's3',
        region_name="eu-central-1",
        aws_access_key_id=AWS_ACCESS_KEY_ID,
        aws_secret_access_key=AWS_SECRET_KEY
    )
