### ISSUE TITLE
Downloaded labels are missing correct spatial properties 

### ISSUE THREAD

**Issue by reidfalconer** [radiantearth/mlhub-tutorials#27]
If one follows the `cv4a-crop-challenge-download-data.ipynb` notebook and downloads the labels (that is 2_label.tif, 1_label.tif, 3_label.tif and 0_label.tif) for some reason these do not have any spatial features i.e. the CRS is missing and the extent is defined as: 

`0.0000000000000000,-3035.0000000000000000 : 2016.0000000000000000,0.0000000000000000`

See QGIS properties:
<img width="1008" alt="qgis_label" src="https://user-images.githubusercontent.com/26482317/81858283-c8b7a180-9563-11ea-8714-9738d6f352bc.png">

Is there a way to correctly download this data so that there correct spatial information is preserved? This would be awesome so that the data can be used in conjunction with other sources. 

Thanks

**Comment by HamedAlemo** [comment]
Hi Reid, 
You are not doing anything wrong, and the files are not Geotiff; they are tiff without any geolocation. This is a pilot for us to test if we can share the data in an anonymized way (matching labels with corresponding imagery, removing location information, and sharing input and target data). 
I understand you would like to match these data with other sources, and it would be great for us to know what are those imagery sources (if they have open access license). We can then include those imagery in the source catalog in future versions. 

For data on Radiant MLHub, we do our best to keep as much information about the labels as possible (other than personally identifiable information). But some of the data providers require us to not share the precise lat/lon of labels, and this is a solution we are testing to be able to share the data, address their requirements and not blur or spatially aggregate the data. 
Having said that, for this particular dataset you have a way to reconstruct the geolocation if you like. When you search on the API if you retrieve the the features from the collection, each one of them has a bbox/geometry that you can use to place the raster image on the map. 


Hamed
